### ISSUE TITLE
Support subresources

### ISSUE THREAD

**Issue by danielpacak** [aquasecurity/kubectl-who-can#22]
Most resources are represented by a string representation of their name, such as "pods", just as it appears in the URL for the relevant API endpoint. However, some Kubernetes APIs involve a "subresource", such as the logs for a pod. The URL for the pods logs endpoint is:

```
GET /api/v1/namespaces/{namespace}/pods/{name}/log
```

In this case, “pods” is the namespaced resource, and “log” is a subresource of pods. To represent this in an RBAC role, use a slash to delimit the resource and subresource. To allow a subject to read both pods and pod logs, you would write:

```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: pod-and-pod-logs-reader
rules:
- apiGroups: [""]
  resources: ["pods", "pods/log"]
  verbs: ["get", "list"]
```

That said we should add the `subresource` flag to the who-can plugin:

```
# Check to see who can read pod logs
$ kubectl who-can get pods --subresource=log

# Check to see who can scale deployments
$ kubectl who-can update deployment --subresource=scale
```
