### ISSUE TITLE
Note in README that --as specifies a User not a ServiceAccount

### ISSUE THREAD

**Issue by lizrice** [aquasecurity/kubectl-who-can#26]
`kubectl-who-can` says my serviceaccount `alice` can get pods, but `kubectl auth can-i` disagrees. 

```bash
rbac $ kubectl-who-can get pods --namespace gotoams
ROLEBINDING            NAMESPACE  SUBJECT  TYPE            SA-NAMESPACE
alice-can-create-pods  gotoams    alice    ServiceAccount  gotoams

CLUSTERROLEBINDING                                    SUBJECT                             TYPE            SA-NAMESPACE
cluster-admin                                         system:masters                      Group
...

rbac $ kubectl auth can-i get pods --namespace gotoams --as alice
no
```

Here's the YAML for the service account, role and rolebinding:
```yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: alice
  namespace: gotoams
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: alice-can-create-pods
  namespace: gotoams
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: can-create-pods
subjects:
- kind: ServiceAccount
  name: alice
  namespace: gotoams
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: can-create-pods
  namespace: gotoams
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - create
  - get
  - list
```
